mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  databases:
    - test1
    - test2
mongodb:
  host: 127.0.0.1
  port: 27017
  user: root
  password: root
  databases:
    - test1
    - test2
wechat:
  corp_id: xxxxx
  agent_id: xxxxx
  secret: xxxxx
  user_id: xxxxx
